#!/bin/bash
###################################################
#
#  Name: add_yum_repos
#  Purpose: Installed the HDP 2.1 yum repo
#  Author: Shane Kumpf
#
###################################################

#
# Base variables
#
SCRIPT_NAME=`basename $0`
SCRIPT_DIR=`cd $(dirname $0) && pwd`

#
# Functions
#
function usage
{
    echo "Usage: $SCRIPT_NAME"
    exit 1
}

#
# Validation
#
if [ `id -un` != "ec2-user" ]; then
    echo "ERROR: Must run as ec2-user"
    exit 1
fi

#
# Variables
#
remote_repo_url="http://public-repo-1.hortonworks.com/HDP/centos6/2.x/GA/2.1-latest/hdp.repo"
repo_match_str="^HDP"

#
# Main
#
echo -e "\nStarting $SCRIPT_NAME at `date`"

# Add the REPO
echo -e "\n#####  Adding repo from $remote_repo_url"
sudo wget -nv $remote_repo_url -O /etc/yum.repos.d/hdp.repo 
echo "SUCCESS"

# locate the latest java install
echo -e "\n#####  Validating that the repo was added"
if ! sudo yum repolist | grep -q "$repo_match_str"; then
    echo "ERROR: Repo does not appear to have been added"
    sudo yum repolist
    exit 1
fi
sudo yum repolist
echo "SUCCESS"

echo -e "\nFinished $SCRIPT_NAME at `date`"
exit 0
