#!/bin/bash
###################################################
#
#  Name: add_yum_repos
#  Purpose: Installed the HDP 2.1 yum repo
#  Author: Shane Kumpf
#
###################################################

#
# Base variables
#
SCRIPT_NAME=`basename $0`
SCRIPT_DIR=`cd $(dirname $0) && pwd`

#
# Functions
#
function usage
{
    echo "Usage: $SCRIPT_NAME -n <node name>"
    exit 1
}

#
# Validation
#
if [ `id -un` != "ec2-user" ]; then
    echo "ERROR: Must run as ec2-user"
    exit 1
fi

#
# Parse command line args
#
while getopts "n:" opt; do
    case $opt in
        n) 
            node=$OPTARG;;
        \?) 
            echo "Invalid option: -$OPTARG"; usage;;
    esac
done

if [ -z "$node" ]; then
    usage
fi

#
# Variables
#
work_dir="/tmp/work"
git_ec2oop_url="https://github.com/sakserv/ec2oop.git"
helpers_dir="$SCRIPT_PATH/../helpers"

ls $helpers_dir

#
# Main
#
echo -e "\nStarting $SCRIPT_NAME at `date`"

# Setup work dir on remote node
echo -e "\n#####  Setup work_dir on remote node"
ec2-ssh $node "test -d $work_dir"
if [ $? -eq 0 ]; then
    echo "Removing and recreating $work_dir on $node"
    ec2-ssh $node "rm -rf $work_dir && mkdir -p $work_dir" || exit 1
    echo "SUCCESS"
else
    echo "Creating $work_dir on $node"
    ec2-ssh $node "mkdir -p $work_dir" || exit 1
    echo "SUCCESS"
fi

# pull down ec2oop repo on remote node
echo -e "\n#####  Pulling repo $git_ec2oop_url on $node"
ec2-ssh $node "cd $work_dir && git clone $git_ec2oop_url" || exit 1
echo "SUCCESS"

echo -e "\nFinished $SCRIPT_NAME at `date`"
exit 0
