#!/bin/bash
###################################################
#
#  Name: init_tez
#  Purpose: Initial tez setup
#  Author: Shane Kumpf
#
###################################################

#
# Base variables
#
SCRIPT_NAME=`basename $0`
SCRIPT_DIR=`cd $(dirname $0) && pwd`

#
# Functions
#
function usage
{
    echo "Usage: $SCRIPT_NAME -t <tez node>"
    exit 1
}

#
# Validation
#
if [ `id -un` != "ec2-user" ]; then
    echo "ERROR: Must run as ec2-user"
    exit 1
fi

#
# Parse command line args
#
while getopts "t:" opt; do
    case $opt in
        t) 
            tez=$OPTARG;;
        \?) 
            echo "Invalid option: -$OPTARG"; usage;;
    esac
done

if [ -z "$tez" ]; then
    usage
fi

#
# Variables
#
work_dir="/tmp/work"
helpers_dir="$work_dir/ec2oop/helpers"
tez_profile_script="/etc/profile.d/tez.sh"

#
# Source helpers
#
source $helpers_dir/scripts/usersAndGroups.sh
source $helpers_dir/scripts/directories.sh

#
# Main
#
echo -e "\nStarting $SCRIPT_NAME at `date`"

# Create the profile.d script for setting tez vars
echo -e "\n#####  Setting tez variables globally"
if ec2-ssh $tez "test -f $tez_profile_script"; then
    ec2-ssh $tez "sudo rm $tez_profile_script" || exit 1
fi

ec2-ssh $tez "echo 'export TEZ_CONF_DIR='$TEZ_CONF_DIR'' | sudo tee -a $tez_profile_script" || exit 1
ec2-ssh $tez "echo 'export TEZ_JARS='$TEZ_JARS'' | sudo tee -a $tez_profile_script" || exit 1
ec2-ssh $tez "echo 'source /etc/hadoop/conf/hadoop-env.sh' | sudo tee -a $tez_profile_script" || exit 1
ec2-ssh $tez "sudo chmod 775 $tez_profile_script" || exit 1
echo "$tez_profile_script contents on $tez:"
ec2-ssh $tez "cat $tez_profile_script" || exit 1
echo "SUCCESS"

# Create the tez app dir
echo -e "\n#####  Creating the tez app dir"
set -x
sudo -u hdfs hdfs dfs -mkdir -p /apps/tez || exit 1
set +x
echo "SUCCESS"

# Copy the tez libs into hdfs
echo -e "\n#####  Copying the tez libs into HDFS"
set -x
sudo -u hdfs hdfs dfs -copyFromLocal /usr/lib/tez/* /apps/tez 
sudo -u hdfs hdfs dfs -chown -R hdfs:hadoop /apps/tez || exit 1
set +x
echo "SUCCESS"

# Enabled tez for hive queries
echo -e "\n#####  Copying the hive libs needed by tez into HDFS"
set -x
sudo -u hdfs hdfs dfs -mkdir -p /apps/hive/install || exit 1
sudo -u hdfs hdfs dfs -copyFromLocal /usr/lib/hive/lib/hive-exec-* /apps/hive/install/ || exit 1
sudo -u hdfs hdfs dfs -chown -R hive:hadoop /apps/hive || exit 1
set +x
echo "SUCCESS"

echo -e "\nFinished $SCRIPT_NAME at `date`"
exit 0
