#!/bin/bash
###################################################
#
#  Name: init_mapred
#  Purpose: Initial mapreduce setup
#  Author: Shane Kumpf
#
###################################################

#
# Base variables
#
SCRIPT_NAME=`basename $0`
SCRIPT_DIR=`cd $(dirname $0) && pwd`

#
# Functions
#
function usage
{
    echo "Usage: $SCRIPT_NAME -h <hive server/metastore>"
    exit 1
}

#
# Validation
#
if [ `id -un` != "ec2-user" ]; then
    echo "ERROR: Must run as ec2-user"
    exit 1
fi

#
# Parse command line args
#
while getopts "h:" opt; do
    case $opt in
        h) 
            hive=$OPTARG;;
        \?) 
            echo "Invalid option: -$OPTARG"; usage;;
    esac
done

if [ -z "$hive" ]; then
    usage
fi

#
# Variables
#
work_dir="/tmp/work"
helpers_dir="$work_dir/ec2oop/helpers"

#
# Source helpers
#
source $helpers_dir/scripts/usersAndGroups.sh
source $helpers_dir/scripts/directories.sh

#
# Main
#
echo -e "\nStarting $SCRIPT_NAME at `date`"

# Create the hive user and warehouse dirs
echo -e "\n#####  Creating the hive user and warehouse directories"
# Hive User
sudo -u hdfs hdfs dfs -mkdir -p /user/hive || exit 1
sudo -u hdfs hdfs dfs -chown $HIVE_USER:$HADOOP_GROUP /user/hive || exit 1
# Hive warehouse
sudo -u hdfs hdfs dfs -mkdir -p /apps/hive/warehouse || exit 1
sudo -u hdfs hdfs dfs -chown $HIVE_USER:$HADOOP_GROUP /apps/hive || exit 1
sudo -u hdfs hdfs dfs -chmod 775 /apps/hive || exit 1
sudo -u hdfs hdfs dfs -chown $HIVE_USER:$HADOOP_GROUP /apps/hive/warehouse || exit 1
sudo -u hdfs hdfs dfs -chmod 775 /apps/hive/warehouse || exit 1
# Hive scratch
sudo -u hdfs hdfs dfs -mkdir -p /tmp/scratch || exit 1
sudo -u hdfs hdfs dfs -chown $HIVE_USER:$HADOOP_GROUP /tmp/scratch || exit 1
sudo -u hdfs hdfs dfs -chmod 777 /tmp/scratch || exit 1
echo "SUCCESS"


# start the metastore
echo -e "\n#####  Starting the metastore on $hive"
if ! ec2-ssh $hive "ps -ef | grep -v grep | grep -q metastore"; then
    ec2-ssh $hive "sudo -u hive nohup hive --service metastore>$HIVE_LOG_DIR/hive.out 2>$HIVE_LOG_DIR/hive.log &" || exit 1
else
    echo -e "\n#####  Skipping start, metastore on $hive already running"
fi
echo "SUCCESS"

# start hiveserver 2
echo -e "\n#####  Starting hiveserver2 on $hive"
if ! ec2-ssh $hive "ps -ef | grep -v grep | grep -qi hiveserver2"; then
    ec2-ssh $hive "sudo -u hive  /usr/lib/hive/bin/hiveserver2 >$HIVE_LOG_DIR/hiveserver2.out 2> $HIVE_LOG_DIR/hiveserver2.log &" || exit 1
else
    echo -e "\n#####  Skipping start, hiveserver2 on $hive already running"
fi
echo "SUCCESS"


echo -e "\nFinished $SCRIPT_NAME at `date`"
exit 0
