#!/bin/bash
###################################################
#
#  Name: init_yarn
#  Purpose: initializes and starts yarn and jhs
#  Author: Shane Kumpf
#
###################################################

#
# Base variables
#
SCRIPT_NAME=`basename $0`
SCRIPT_DIR=`cd $(dirname $0) && pwd`

#
# Functions
#
function usage
{
    echo "Usage: $SCRIPT_NAME -r <resourcemanager> -n \"<nodemanager1 [nodemanager2...]>\""
    exit 1
}

#
# Validation
#
if [ `id -un` != "ec2-user" ]; then
    echo "ERROR: Must run as ec2-user"
    exit 1
fi

#
# Parse command line args
#
while getopts "r:n:" opt; do
    case $opt in
        r) 
            resm=$OPTARG;;
        n)
            nm_list="$OPTARG";;
        \?) 
            echo "Invalid option: -$OPTARG"; usage;;
    esac
done

if [ -z "$resm" ]; then
    usage
fi

if [ -z "$nm_list" ]; then
    usage
fi

#
# Variables
#
work_dir="/tmp/work"
git_ec2oop_url="https://github.com/sakserv/ec2oop.git"
git_ec2_tools_url=" https://github.com/sakserv/ec2-tools"
helpers_dir="$work_dir/ec2oop/helpers"

#
# Prep work dir
#
for node in $resm $nm_list; do
    echo -e "\n#####  Setting up $work_dir on $node"
    if ec2-ssh $node "test -d $work_dir";  then
        echo -e "\n#####  Cleaning up previous work directory $work_dir"
        ec2-ssh $node "rm -rf $work_dir" || exit 1
        echo "SUCCESS"
    fi

    # Create new work dir
    if ! ec2-ssh $node "test -d $work_dir";  then
        echo -e "\n#####  Creating work directory $work_dir"
        ec2-ssh $node "mkdir -p $work_dir" || exit 1
        echo "SUCCESS"
    fi

    # git clone ec2-tools into work dir
    echo -e "\n#####  Cloning ec2-tools repo"
    ec2-ssh $node "(cd $work_dir && git clone $git_ec2_tools_url)" || exit 1
    echo "SUCCESS"

    # git clone ec2oop into work dir
    echo -e "\n#####  Pulling repo $git_ec2oop_url to $work_dir"
    ec2-ssh $node "(cd $work_dir && git clone $git_ec2oop_url)" || exit 1
    echo "SUCCESS"
done

#
# Source helpers
#
source $helpers_dir/scripts/usersAndGroups.sh
source $helpers_dir/scripts/directories.sh

#
# Main
#
echo -e "\nStarting $SCRIPT_NAME at `date`"

# Create the yarn user directory in hdfs
echo -e "\n#####  Creating the yarn user directory in hdfs"
sudo -u hdfs hdfs dfs -mkdir -p /user/yarn || exit 1
sudo -u hdfs hdfs dfs -chmod -R 775 /user/yarn || exit 1
sudo -u hdfs hdfs dfs -chown -R yarn:hadoop /user/yarn || exit 1
echo "SUCCESS"

# Create the hdfs /app-logs directory for log aggregation
echo -e "\n#####  Creating the remote app log dir for log aggregation"
sudo -u hdfs hdfs dfs -mkdir -p /app-logs || exit 1
sudo -u hdfs hdfs dfs -chmod -R 1777 /app-logs || exit 1
sudo -u hdfs hdfs dfs -chown -R yarn /app-logs || exit 1
echo "SUCCESS"

# start the RM
echo -e "\n#####  Starting the resourcemanager $resm"
if ! ec2-ssh $resm "ps -ef | grep -v grep | grep -q proc_resourcemanager"; then
    ec2-ssh $resm "sudo -u yarn HADOOP_LIBEXEC_DIR=/usr/lib/hadoop/libexec /usr/lib/hadoop-yarn/sbin/yarn-daemon.sh --config $HADOOP_CONF_DIR start resourcemanager" || exit 1
else
    echo "Skipping start, resourcemanager $rm already running"
fi
echo "SUCCESS"

# start the nodemanagers
for nm in $nm_list; do
  
    echo -e "\n#####  Fixing container-executor perms for nodemanager $nm"
    ec2-ssh $nm "sudo chown -R root:hadoop /usr/lib/hadoop-yarn/bin/container-executor" || exit 1
    ec2-ssh $nm "sudo chmod -R 6050 /usr/lib/hadoop-yarn/bin/container-executor" || exit 1
    echo "SUCCESS"

    echo -e "\n#####  Starting the nodemanager $nm"
    if ! ec2-ssh $nm "ps -ef | grep -v grep | grep -q proc_nodemanager"; then
        ec2-ssh $nm "sudo -u yarn HADOOP_LIBEXEC_DIR=/usr/lib/hadoop/libexec /usr/lib/hadoop-yarn/sbin/yarn-daemon.sh --config $HADOOP_CONF_DIR start nodemanager" || exit 1
    else
        echo "Skipping start, nodemanager $nm already running"
    fi
    echo "SUCCESS"

done

echo -e "\nFinished $SCRIPT_NAME at `date`"
exit 0
