#!/bin/bash
###################################################
#
#  Name: init_yarn
#  Purpose: initializes and starts yarn and jhs
#  Author: Shane Kumpf
#
###################################################

#
# Base variables
#
SCRIPT_NAME=`basename $0`
SCRIPT_DIR=`cd $(dirname $0) && pwd`

#
# Functions
#
function usage
{
    echo "Usage: $SCRIPT_NAME -n <nimbus> -w \"<stormworker1 [stormworker2...]>\""
    exit 1
}

#
# Validation
#
if [ `id -un` != "ec2-user" ]; then
    echo "ERROR: Must run as ec2-user"
    exit 1
fi

#
# Parse command line args
#
while getopts "n:w:" opt; do
    case $opt in
        n) 
            nimbus=$OPTARG;;
        w)
            sw_list="$OPTARG";;
        \?) 
            echo "Invalid option: -$OPTARG"; usage;;
    esac
done

if [ -z "$nimbus" ]; then
    usage
fi

if [ -z "$sw_list" ]; then
    usage
fi

#
# Variables
#
work_dir="/tmp/work"
git_ec2oop_url="https://github.com/sakserv/ec2oop.git"
git_ec2_tools_url=" https://github.com/sakserv/ec2-tools"
helpers_dir="$work_dir/ec2oop/helpers"

#
# Prep work dir
#
for node in $resm $nm_list; do
    echo -e "\n#####  Setting up $work_dir on $node"
    if ec2-ssh $node "test -d $work_dir";  then
        echo -e "\n#####  Cleaning up previous work directory $work_dir"
        ec2-ssh $node "rm -rf $work_dir" || exit 1
        echo "SUCCESS"
    fi

    # Create new work dir
    if ! ec2-ssh $node "test -d $work_dir";  then
        echo -e "\n#####  Creating work directory $work_dir"
        ec2-ssh $node "mkdir -p $work_dir" || exit 1
        echo "SUCCESS"
    fi

    # git clone ec2-tools into work dir
    echo -e "\n#####  Cloning ec2-tools repo"
    ec2-ssh $node "(cd $work_dir && git clone $git_ec2_tools_url)" || exit 1
    echo "SUCCESS"

    # git clone ec2oop into work dir
    echo -e "\n#####  Pulling repo $git_ec2oop_url to $work_dir"
    ec2-ssh $node "(cd $work_dir && git clone $git_ec2oop_url)" || exit 1
    echo "SUCCESS"
done

#
# Source helpers
#
source $helpers_dir/scripts/usersAndGroups.sh
source $helpers_dir/scripts/directories.sh

#
# Main
#
echo -e "\nStarting $SCRIPT_NAME at `date`"

# start the RM
echo -e "\n#####  Starting nimbus, drpc, and web ui on $nimbus"
ec2-ssh $nimbus "sudo service supervisord start" || exit 1
echo "SUCCESS"

# start the nodemanagers
for sw in $sw_list; do
    echo -e "\n#####  Starting supervisor and logviewer on $sw"
    ec2-ssh $sw "sudo service supervisord start" || exit 1
    echo "SUCCESS"
done

echo -e "\nFinished $SCRIPT_NAME at `date`"
exit 0
