#!/bin/bash
###################################################
#
#  Name: init_zk
#  Purpose: Initial zookeeper setup
#  Author: Shane Kumpf
#
###################################################

#
# Base variables
#
SCRIPT_NAME=`basename $0`
SCRIPT_DIR=`cd $(dirname $0) && pwd`

#
# Functions
#
function usage
{
    echo "Usage: $SCRIPT_NAME -z \"<zookeeper1> [<zookeeper2>...]\""
    exit 1
}

#
# Validation
#
if [ `id -un` != "ec2-user" ]; then
    echo "ERROR: Must run as ec2-user"
    exit 1
fi

#
# Parse command line args
#
while getopts "z:" opt; do
    case $opt in
        z) 
            zk_list=$OPTARG;;
        \?) 
            echo "Invalid option: -$OPTARG"; usage;;
    esac
done

if [ -z "$zk_list" ]; then
    usage
fi

#
# Variables
#
work_dir="/tmp/work"
git_ec2oop_url="https://github.com/sakserv/ec2oop.git"
git_ec2_tools_url=" https://github.com/sakserv/ec2-tools"
helpers_dir="$work_dir/ec2oop/helpers"

#
# Prep work dir
#
for node in $zk_list; do
    echo -e "\n#####  Setting up $work_dir on $node"
    if ec2-ssh $node "test -d $work_dir";  then
        echo -e "\n#####  Cleaning up previous work directory $work_dir"
        ec2-ssh $node "rm -rf $work_dir" || exit 1
        echo "SUCCESS"
    fi

    # Create new work dir
    if ! ec2-ssh $node "test -d $work_dir";  then
        echo -e "\n#####  Creating work directory $work_dir"
        ec2-ssh $node "mkdir -p $work_dir" || exit 1
        echo "SUCCESS"
    fi

    # git clone ec2-tools into work dir
    echo -e "\n#####  Cloning ec2-tools repo"
    ec2-ssh $node "(cd $work_dir && git clone $git_ec2_tools_url)" || exit 1
    echo "SUCCESS"

    # git clone ec2oop into work dir
    echo -e "\n#####  Pulling repo $git_ec2oop_url to $work_dir"
    ec2-ssh $node "(cd $work_dir && git clone $git_ec2oop_url)" || exit 1
    echo "SUCCESS"
done

#
# Source helpers
#
source $helpers_dir/scripts/usersAndGroups.sh
source $helpers_dir/scripts/directories.sh

#
# Main
#
echo -e "\nStarting $SCRIPT_NAME at `date`"

for zk in $zk_list; do
    myid=`echo $zk | sed 's|[^0-9]||g'`
    echo -e "\n#####  Initializing myid file for $zk with id $myid"
    if ! ec2-ssh $zk "test -f $ZOOKEEPER_DATA_DIR/myid"; then
        ec2-ssh $zk "echo $count | sudo -u zookeeper tee $ZOOKEEPER_DATA_DIR/myid" || exit 1
    else
        echo "Skipping myid creation, $ZOOKEEPER_DATA_DIR/myid already exists on $zk"
    fi
done
echo "SUCCESS"


# start the zk ensemble
for zk in $zk_list; do
    echo -e "\n#####  Starting the zookeeper node $zk"
    if ! ec2-ssh $zk "ps -ef | grep -v grep | grep -q QuorumPeerMain"; then
        ec2-ssh $zk "sudo -u zookeeper ZOOCFGDIR=/etc/zookeeper/conf /usr/lib/zookeeper/bin/zkServer.sh start | sudo -u zookeeper tee /var/log/zookeeper/zoo.out 2>&1" || exit 1
    else
        echo -e "\n#####  Skipping start, zookeeper node $zk already running"
    fi
done
echo "SUCCESS"

echo -e "\nFinished $SCRIPT_NAME at `date`"
exit 0
