#!/bin/bash
###################################################
#
#  Name: init_yarn
#  Purpose: initializes and starts yarn and jhs
#  Author: Shane Kumpf
#
###################################################

#
# Base variables
#
SCRIPT_NAME=`basename $0`
SCRIPT_DIR=`cd $(dirname $0) && pwd`

#
# Functions
#
function usage
{
    echo "Usage: $SCRIPT_NAME -r <resourcemanager> -n \"<nodemanager1 [nodemanager2...]>\""
    exit 1
}

#
# Validation
#
if [ `id -un` != "ec2-user" ]; then
    echo "ERROR: Must run as ec2-user"
    exit 1
fi

#
# Parse command line args
#
while getopts "r:n:" opt; do
    case $opt in
        r) 
            resm=$OPTARG;;
        n)
            nm_list="$OPTARG";;
        \?) 
            echo "Invalid option: -$OPTARG"; usage;;
    esac
done

if [ -z "$resm" ]; then
    usage
fi

if [ -z "$nm_list" ]; then
    usage
fi

#
# Variables
#
work_dir="/tmp/work"
helpers_dir="$work_dir/ec2oop/helpers"

#
# Source helpers
#
source $helpers_dir/scripts/usersAndGroups.sh
source $helpers_dir/scripts/directories.sh

#
# Main
#
echo -e "\nStarting $SCRIPT_NAME at `date`"

# stop the nodemanagers
for nm in $nm_list; do
    echo -e "\n#####  Stopping the nodemanager $nm"
    if ec2-ssh $nm "ps -ef | grep -v grep | grep -q proc_nodemanager"; then
        ec2-ssh $nm "sudo -u yarn HADOOP_LIBEXEC_DIR=/usr/lib/hadoop/libexec /usr/lib/hadoop-yarn/sbin/yarn-daemon.sh --config $HADOOP_CONF_DIR stop nodemanager" || exit 1
    else
        echo -e "\n#####  Skipping stop, nodemanager $nm already stopped"
    fi
    echo "SUCCESS"
done

# stop the RM
echo -e "\n#####  Stopping the resourcemanager $resm"
if ec2-ssh $resm "ps -ef | grep -v grep | grep -q proc_resourcemanager"; then
    ec2-ssh $resm "sudo -u yarn HADOOP_LIBEXEC_DIR=/usr/lib/hadoop/libexec /usr/lib/hadoop-yarn/sbin/yarn-daemon.sh --config $HADOOP_CONF_DIR stop resourcemanager" || exit 1
else
    echo -e "\n#####  Skipping stop, resourcemanager $rm already stopped"
fi
echo "SUCCESS"

echo -e "\nFinished $SCRIPT_NAME at `date`"
exit 0
