#!/bin/bash
###################################################
#
#  Name: stop_mapred
#  Purpose: stop the JHS mapreduce service
#  Author: Shane Kumpf
#
###################################################

#
# Base variables
#
SCRIPT_NAME=`basename $0`
SCRIPT_DIR=`cd $(dirname $0) && pwd`

#
# Functions
#
function usage
{
    echo "Usage: $SCRIPT_NAME -j <jobhistoryserver>"
    exit 1
}

#
# Validation
#
if [ `id -un` != "ec2-user" ]; then
    echo "ERROR: Must run as ec2-user"
    exit 1
fi

#
# Parse command line args
#
while getopts "j:" opt; do
    case $opt in
        j) 
            jhs=$OPTARG;;
        \?) 
            echo "Invalid option: -$OPTARG"; usage;;
    esac
done

if [ -z "$jhs" ]; then
    usage
fi

#
# Variables
#
work_dir="/tmp/work"
helpers_dir="$work_dir/ec2oop/helpers"

#
# Source helpers
#
source $helpers_dir/scripts/usersAndGroups.sh
source $helpers_dir/scripts/directories.sh

#
# Main
#
echo -e "\nStarting $SCRIPT_NAME at `date`"

# start the JHS
echo -e "\n#####  Stopping the jobhistoryserver $jhs"
if ec2-ssh $jhs "ps -ef | grep -v grep | grep -q proc_historyserver"; then
    ec2-ssh $jhs "sudo -u mapred HADOOP_LIBEXEC_DIR=/usr/lib/hadoop/libexec/ /usr/lib/hadoop-mapreduce/sbin/mr-jobhistory-daemon.sh --config $HADOOP_CONF_DIR stop historyserver" || exit 1
else
    echo -e "\n#####  Skipping stop, jobhistoryserver $jhs already stopped"
fi
echo "SUCCESS"

echo -e "\nFinished $SCRIPT_NAME at `date`"
exit 0
