#!/bin/bash
###################################################
#
#  Name: test_harness
#  Purpose: validate functionality of the cluster
#  Author: Shane Kumpf
#
###################################################

#
# Base variables
#
SCRIPT_NAME=`basename $0`
SCRIPT_DIR=`cd $(dirname $0) && pwd`

#
# Functions
#
function usage
{
    echo "Usage: $SCRIPT_NAME"
    exit 1
}

#
# Validation
#
if [ `id -un` != "ec2-user" ]; then
    echo "ERROR: Must run as ec2-user"
    exit 1
fi

#
# Parse command line args
#
while getopts "n:s:d:" opt; do
    case $opt in
        n) 
            nn=$OPTARG;;
        s) 
            snn=$OPTARG;;
        d)
            dn_list="$OPTARG";;
        \?) 
            echo "Invalid option: -$OPTARG"; usage;;
    esac
done

#
# Variables
#
work_dir="/tmp/work"
git_ec2oop_url="https://github.com/sakserv/ec2oop.git"
git_ec2_tools_url=" https://github.com/sakserv/ec2-tools"
helpers_dir="$work_dir/ec2oop/helpers"

#
# Prep work dir
#

#
# Main
#
echo -e "\nStarting $SCRIPT_NAME at `date`"

echo -e "\n#####  Listing HDFS root"
sudo -u hdfs hdfs dfs -ls / || exit 1
echo "SUCCESS"

echo -e "\n#####  Running teragen"
hadoop jar /usr/lib/hadoop-mapreduce/hadoop-mapreduce-examples.jar teragen 10000 /tmp/teragenout || exit 1
echo "SUCCESS"

echo -e "\n#####  Running terasort"
hadoop jar /usr/lib/hadoop-mapreduce/hadoop-mapreduce-examples.jar terasort /tmp/teragenout /tmp/terasortout || exit 1
echo "SUCCESS"

echo -e "\n#####  Show hive databases"
hive -e "show databases;" || exit 1
echo "SUCCESS"

echo -e "\nFinished $SCRIPT_NAME at `date`"
exit 0
